openapi: 3.0.2
info:
  title: XXX API Document
  version: ''
paths:
  /tapp/products/:
    get:
      operationId: listProducts
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        name:
                          type: string
                          maxLength: 100
                        price:
                          type: integer
          description: ''
    post:
      operationId: createProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
          multipart/form-data:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 100
                  price:
                    type: integer
          description: ''
  /tapp/products/{id}/:
    get:
      operationId: retrieveProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 100
                  price:
                    type: integer
          description: ''
    put:
      operationId: updateProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
          multipart/form-data:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 100
                  price:
                    type: integer
          description: ''
    patch:
      operationId: partial_updateProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
          multipart/form-data:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 100
                price:
                  type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 100
                  price:
                    type: integer
          description: ''
    delete:
      operationId: destroyProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this product.
        schema:
          type: string
      responses:
        '204':
          description: ''